---
downloads: ~/.ansible/downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/lhazlewood/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: "{{ ansible_env.HOME }}/projects/lhazlewood/dotfiles"
dotfiles_files:
  - .bash_profile
  - .bashrc
  - .osx
  - .zshenv
  - .zshrc

homebrew_installed_packages:
#- autoconf
- bash-completion
- zsh-completions
#- doxygen
#- gettext
#- gifsicle
- git
#- go
- gpg
- hub
- httpie
#- iperf
#- libevent
#- sqlite
#- mcrypt
#- nmap
#- node
#- nvm
#- php
#- ssh-copy-id
#- cowsay
#- readline
#- openssl
#- pv
#- wget
#- wrk
- liquidprompt

homebrew_taps:
- homebrew/core
- homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - iterm2
#- chromedriver
#- docker
#- dropbox
#- firefox
#- google-chrome
#- handbrake
#- licecap
#- limechat
#- macvim
#- sequel-pro
#- skitch
#- slack
#- sublime-text
#- transmit
#- vagrant

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
